In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from IPython.display import Image
np.set_printoptions(precision = 3)

In [2]:
data = pd.read_csv("jester-data-1.csv", header=None)
data.head()

0      1      2      3      4     5     6     7     8      9    ...    \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...     
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...     
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...     
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...     
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

In [4]:
data = data.head(50)
data.shape

(50, 101)

In [5]:
alpha = 0.001
iterations = 30
k = 5
n_features = 2

In [11]:
dataset = data[data.applymap(lambda x: x!=99)]

In [12]:
narray = np.array(new_data)
print(narray)

[[ 74.    -7.82   8.79 ...    nan    nan    nan]
 [100.     4.08  -0.29 ...   0.34  -4.32   1.07]
 [ 49.      nan    nan ...    nan    nan    nan]
 ...
 [ 89.    -8.25  -1.17 ...   2.23   0.68   5.39]
 [ 71.    -5.44   0.68 ...    nan    nan    nan]
 [100.    -7.82   9.17 ...  -9.27   1.46   8.06]]


In [13]:
#Train the indices

tr_indices = np.argwhere(~np.isnan(narray))
null_indices = np.argwhere(np.isnan(narray))

print(tr_indices)

[[  0   0]
 [  0   1]
 [  0   2]
 ...
 [ 49  98]
 [ 49  99]
 [ 49 100]]


In [16]:
user_ratings = dataset.values
Upreferences = np.random.random((user_ratings.shape[0], n_features))
itemfeatures = np.random.random((user_ratings.shape[1],n_features))
print("The latent user preferences feature size:  ", Upreferences.shape)
print("The latent jokes feature size is ", item_features.shape)

The latent user preferences feature size:   (50, 2)
The latent jokes feature size is  (101, 2)


In [18]:
def predict_rating(user_id,item_id,latent_user_preferences, latent_item_features):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating, latent_user_preferences, latent_item_features, alpha = 0.001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id,latent_user_preferences, latent_item_features)
    err =  ( prediction_rating- rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err, latent_user_preferences, latent_item_features

In [24]:
def sgd(fold_train, fold_test,latent_user_preferences, latent_item_features, iterations = 50):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    
    train_mse = 0 
    test_mse = 0
    
    for iteration in range(0,iterations):
        error = []
        for i,j in fold_train:
            user_id = fold_train[i][0]
            item_id = fold_train[i][1]
            rating = user_ratings[i][j]
            train_err,latent_user_preferences, latent_item_features= train(user_id, 
                                                                           item_id, rating, 
                                                                           latent_user_preferences, 
                                                                           latent_item_features, alpha = 0.001)
            error.append(train_err)
       
        train_mse = (np.array(error) ** 2).mean()   
        
    
    test_error =[]
    for i,j in fold_test:
        user_id = fold_test[i][0]
        item_id = fold_test[i][1]
        rating = user_ratings[i][j]
        err  =user_ratings[i][j]- predict_rating(user_id, item_id,latent_user_preferences, latent_item_features)
        test_error.append(err)
    
    test_mse = (np.array(test_error) ** 2).mean()   
    #print("test mse ",test_mse)
    
    return (train_mse, test_mse)

In [23]:
kf = KFold(n_splits=k)
for train_ind, test_ind in kf.split(train_indices):
    fold_train = train_indices[train_ind]
    fold_test = train_indices[test_ind]
    latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
    latent_item_features = np.random.random((user_ratings.shape[1],n_features))
    train_mse, test_mse = sgd(fold_train, fold_test,latent_user_preferences, latent_item_features)
    print("The Train MSE is: "+ str(train_mse) )
    print("The Test MSE is: "  + str(test_mse))

The Train MSE is: 92.50267972184164
The Test MSE is: 119.23021800210549
The Train MSE is: 95.21854190843595
The Test MSE is: 100.92593976130837
The Train MSE is: 96.99882428711561
The Test MSE is: 93.26295501983118
The Train MSE is: 99.55888149145987
The Test MSE is: 86.30592348758012
The Train MSE is: 92.87407860987557
The Test MSE is: 115.86618054594088
